### ISSUE TITLE
[FR] add dialpad

### ISSUE THREAD

**Issue by thundergreen** [TECH7Fox/asterisk-hass-integration#27]
I have setup some conferences. My goal is to call a person and invite diretly into a conference. Like this all my devices inside my house are "connected"

**Comment by pergolafabio** [comment]
yes, would love this functionality too, for doorbell scenario

somekind of addressbook to add on list would be nice, or predefined numbers

**Comment by TECH7Fox** [comment]
Fixed with the `custom` options.
