### ISSUE TITLE
Detected blocking call to sleep inside the event loop. This is causing stability issues.

### ISSUE THREAD

**Issue by nanosonde** [TECH7Fox/asterisk-hass-integration#48]
Hi!

Just found this in my logs. Should be fixed. In general calling something like sleep() in an event loop's main thread is bad practise.

Logger: homeassistant.util.async_
Source: util/async_.py:150
First occurred: 14:38:03 (1 occurrences)
Last logged: 14:38:03

Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom component author for asterisk doing blocking calls at custom_components/asterisk/__init__.py, line 101: sleep(5)

**Comment by TECH7Fox** [comment]
Removed it. :)
