### ISSUE TITLE
Fix handling of pjsip endpoints events

### ISSUE THREAD

**Issue by nanosonde** [TECH7Fox/asterisk-hass-integration#49]
and remove old SIP module handling.

See 
https://wiki.asterisk.org/wiki/display/AST/Asterisk+18+ManagerAction_PJSIPShowEndpoints

https://wiki.asterisk.org/wiki/display/AST/Asterisk+18+ManagerEvent_EndpointList

https://wiki.asterisk.org/wiki/display/AST/Asterisk+18+ManagerEvent_EndpointListComplete

Maybe we can also use this:
https://wiki.asterisk.org/wiki/display/AST/Asterisk+18+ManagerAction_ExtensionState

**Comment by TECH7Fox** [comment]
Now got all events for pjsip working. Used [DeviceStateChange](https://wiki.asterisk.org/wiki/display/AST/Asterisk+18+ManagerEvent_DeviceStateChange) for the state so doesn't have to poll.
