### ISSUE TITLE
Use python_ami

### ISSUE THREAD

**Issue by TECH7Fox** [TECH7Fox/asterisk-hass-integration#57]
Pyst2 is no longer maintained and has some bugs like reconnecting.

[Python_ami](https://github.com/ettoreleandrotognoli/python-ami) seem's actively maintained and has a working reconnect function.

**Comment by TECH7Fox** [comment]
If I reload the module, all the entities would no longer work so the integration would need to fully reload and setup the new entities. And I don't really know how to do that, or if that is even possible.

The python_ami library does fully work, but it is quite some work to convert the integration to this. I did make a small start.

I do now see some new commits on pyst2. But unless this issue get's fixed soon, I will just use python_ami.

**Comment by TimelessNL** [comment]
> the integration would need to fully reload and setup the new entities. And I don't really know how to do that, or if that is even possible.

If I'm not mistaken this has now been implemented in #65 😃, so restarting the integration on a disconnect could be an option now?

**Comment by TECH7Fox** [comment]
> so restarting the integration on a disconnect could be an option now?

Yes indeed.

But the python-ami branch got merged, so it should stay connected now.
