### ISSUE TITLE
Extension Shows as Unavailable after upgrading HA to 7

### ISSUE THREAD

**Issue by msettlemeyer** [TECH7Fox/asterisk-hass-integration#58]
After upgraded HassOS to version 7, my only extension is no longer available. My trunk entity and my server entity are still working, but my extension isn't. When I deleted and added the integration again, it doesn't find the extension anymore. Any troubleshooting advice would be greatly appreciated.

**Comment by msettlemeyer** [comment]
Nothing. Today, when I visited the integrations page to delete it and see if anything shows up when I add it back. It looks like the extension is showing up now. I guess this can be closed. Thanks for the response. If I see anything happen again, I'll report.

**Comment by TECH7Fox** [comment]
Good it works again. 🙂 The integration is still in alpha, so weird behaviour like this is expected for now. Probably bad timing between asterisk and the integration starting. Please reopen when this happens again.

**Comment by msettlemeyer** [comment]
Will do. Nice job so far. 🙂 I use it mainly to monitor my instance for outages and send caller id to me around the house.
