### ISSUE TITLE
Not all FreePBX extensions show up

### ISSUE THREAD

**Issue by RolandWijnen** [TECH7Fox/asterisk-hass-integration#60]
Hi, 

I've installed SIP card and Asterisk integration. I see that both SIP and PJSIP extensions are recognized by the integration. See screenshot. However, not all of the extensions that I have setup in FreePBX show up in Home Assistant. I cannot immediately see why that is. Is there some specific setting needed in FreePBX so that extensions are imported by the Asterisk extension?
<img width="1190" alt="Screen Shot 2022-08-31 at 23 13 35" src="https://user-images.githubusercontent.com/24925747/187786174-d3f5a9af-f833-456d-a9b2-d0cb2929e351.png">

**Comment by RolandWijnen** [comment]
I've done some more testing. Yesterday, I deleted and reinstalled the integration a couple of times. One time it discovered only 4 devices (extensions) but before that is discovered 12. The most recent install of the integration shows 9 devices.

Could it be that the integration setup gets stuck interacting with Asterisk (I'm using FreePBX 16.0.21.9)? 

<img width="1203" alt="Screen Shot 2022-09-02 at 09 29 20" src="https://user-images.githubusercontent.com/24925747/188083356-6fffcd90-508a-47fc-9879-5f98da0e93bf.png">

**Comment by TECH7Fox** [comment]
Not sure. Do you have any errors in the HA logs?
The integration will be migrated to another library, do that could fix it.

**Comment by RolandWijnen** [comment]
Thanks! No errors in the HA logs. Funny thing is that today a couple of more extensions were added. I guess that it just takes some time to discover all the extensions. Only one is still missing, but that is ok. So I'm good for now. Will continue with setting up the card itself and testing it.
