### ISSUE TITLE
Integration started before Asterisk addon fails to connect

### ISSUE THREAD

**Issue by pluskal** [TECH7Fox/asterisk-hass-integration#61]
During a full system reboot, it happens that this integration starts before the asterisk addon, resulting in the following error.

```
This error originated from a custom integration.

Logger: custom_components.asterisk
Source: custom_components/asterisk/__init__.py:154
Integration: Asterisk (documentation, issues)
First occurred: 9:09:18 AM (1 occurrences)
Last logged: 9:09:18 AM

Error connecting to Asterisk: Connection refused
```

Would it be possible to use retry logic to overcome this?

A workaround seems to be to restart Home Assistant after the addon starts.

**Comment by TECH7Fox** [comment]
Yes this is a known issue, that should be fixed by retrying to connect. But the library used has a bug that makes that impossible. So I'm gonna switch to a new maintained library, just haven't got around to it.

**Comment by TECH7Fox** [comment]
Will be fixed by #57

**Comment by TimelessNL** [comment]
This is possibly also the reason that if Asterisk is restarted the integration does not re-connect to the AMI interface and requires a Hass restart? If so, any update on this 😊?

**Comment by TECH7Fox** [comment]
For startup this got fixed. The integration now retries startup until it connects. It still crashes if it disconnects after startup, but you can manually reload it for now. Let me know if you got any issues left.

**Comment by niraviry** [comment]
I have somewhat similar situation but since there is no other post about it I will detail it here.
The add-on does not connect and the error is:

> Connection error while connecting to localhost:5038: Connection refused
When dumping the log I get the following:

> [homeassistant.config_entries] Config entry 'localhost' for asterisk integration not ready yet: Connection error while connecting to localhost:5038: Connection refused; Retrying in background

Sometimes it works after a HA restart OK but most of the time it does not.
It usually happens after an HA Core update is being performed and after the HA restart it is stuck in this state.

**Comment by TECH7Fox** [comment]
@niraviry are you restarting the add-on?  Then it crashes and you need to manually reload the integration for now. But when restarting the entire HA, it should retry until succeeding.

Do you have the latest version of the integration?

**Comment by niraviry** [comment]
I do have the latest version and it is true for all last 4 versions or so.

**Comment by niraviry** [comment]
Any suggestions?

**Comment by TECH7Fox** [comment]
@niraviry it's weird. Normally the integration should only stop working when the add-on is restarting, not the other way around.
Is there anything in the asterisk logs?

**Comment by niraviry** [comment]
HA logs while filtering for Asterisk in the main log shows the above error twice and that's it.
Don't mind the Hebrew. It is just the date. It is still in the same state for a few days. It might fix itself whenever it fills.
If choosing Asterisk from the side list of integrations and add-ons, no errors at all.

Any other location to get the log?

> Logger: homeassistant.config_entries
Source: config_entries.py:1113
First occurred: 24 בדצמבר 2022 בשעה 19:35:07 (6 occurrences)
Last logged: 26 בדצמבר 2022 בשעה 13:33:48

Config entry 'localhost' for asterisk integration not ready yet: Connection error while connecting to localhost:5038: Connection refused; Retrying in background

**Comment by niraviry** [comment]
Just rebooted HA again due to other reseaon (LG Integration update) and now it is OK.

**Comment by niraviry** [comment]
After a quite 2 months, after a power outage, I got the same issue I was complaining about. The integration refuses to load although I only powered the RPi on again.
I got the following in the log (I did not touch anything in the configuration till the power outage):

`s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Asterisk
 PBX server for SIP devices like doorbells and phones
-----------------------------------------------------------
 Add-on version: 2.3.5
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.2.3
 Home Assistant Supervisor: 2023.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-timezone: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
[12:39:46] INFO: Configuring timezone (Asia/Jerusalem)...
s6-rc: info: service base-addon-timezone successfully started
Log level is set to INFO
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/asterisk.sh
[12:39:47] INFO: Configuring certificate...
[12:39:47] INFO: Using existing certificate as 'generate_ssl_certificate' is disabled...
[12:39:48] INFO: Configuring Asterisk...
parse error: Expected string key before ':' at line 1, column 4
cont-init: info: /etc/cont-init.d/asterisk.sh exited 4
cont-init: info: running /etc/cont-init.d/asterisk_mbox.sh
cont-init: info: /etc/cont-init.d/asterisk_mbox.sh exited 0
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-timezone: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service base-addon-timezone successfully stopped
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped`

I need help. I can remind you that the last time was solved without anything I have changed but only re-booting after many re-boots.
