### ISSUE TITLE
Consolidate NOT IN USE state

### ISSUE THREAD

**Issue by felipecrs** [TECH7Fox/asterisk-hass-integration#68]
![image](https://user-images.githubusercontent.com/29582865/208792458-ecae1918-df85-4bd0-aee0-ad82ba975ac2.png)

**Comment by TECH7Fox** [comment]
Hmm. Weird. It is directly the state Asterisk gives.

**Comment by felipecrs** [comment]
So maybe this is an issue in the library the integration uses. I'll follow up.

**Comment by felipecrs** [comment]
Oh no. You are right. Most likely this is an issue in Asterisk itself. Sad.

**Comment by felipecrs** [comment]
`NOT IN USE` only appears when the integration is first loaded/reload. Could this be because of this?

![image](https://user-images.githubusercontent.com/29582865/208919922-4e719dd4-6321-44b4-ab21-38acfbfd5fe4.png)

**Comment by felipecrs** [comment]
Yeah, this is actually how the issue is fixed for me:

```python
def __init__(self, hass, status, extension, tech, entry):
        """Setting up extension."""
        self._hass = hass
        self._astmanager = hass.data[DOMAIN][entry.entry_id]["manager"]
        self._extension = extension
        self._state = "NOT_INUSE" if status == "NOT IN USE" else status
        self._tech = tech
        self._entry = entry
        self._unique_id = f"{entry.entry_id}_{extension}_state"
        self._astmanager.register_event("DeviceStateChange", self.handle_asterisk_event)
```

The question is, where do this "status" comes from?

**Comment by TECH7Fox** [comment]
Asterisk gives the state in a different format in some events then others, which is kinda weird but I've mapped them to be consistant now. Please reopen if you still get unexpected states.

**Comment by felipecrs** [comment]
Thanks a ton!
