### ISSUE TITLE
Can I use the integration to detect when someone pressed the doorbell button?

### ISSUE THREAD

**Issue by felipecrs** [TECH7Fox/asterisk-hass-integration#69]
I was thinking about using the State entity, but it also goes to `INUSE` when I call the extension from my side.

**Comment by felipecrs** [comment]
Actually yes. I think I can use the Callee entity. When the doorbell calls the conference room it is set to `<unknown>`, that should be enough.

**Comment by felipecrs** [comment]
@TECH7Fox the only issue I noticed is that after some hours, the entity stopped being updated. I had to manually reload the integration. Is this a known issue?

**Comment by TECH7Fox** [comment]
> the only issue I noticed is that after some hours, the entity stopped being updated.

Shouldn't happen anymore with v1.0.0.
