### ISSUE TITLE
authentication failed

### ISSUE THREAD

**Issue by tung256** [TECH7Fox/asterisk-hass-integration#72]
hello. i am starting from scratch. there is no PBX server except the one i will install onto my HA machine.
i was able to get the add-on up and running as seen here from the Add-On Store
![image](https://user-images.githubusercontent.com/37672036/226102126-53a68f9a-1d3e-41f6-943e-cb0a1642cdd7.png)
in the Config tab, i put in my password:  password123
![image](https://user-images.githubusercontent.com/37672036/226102162-d4b74960-13dc-48e9-8c87-b5ed25ef2743.png)
can it be any password or do i create another for user named "admin" in my HA machine? as of now, no user named "admin" for my HA machine.
![image](https://user-images.githubusercontent.com/37672036/226102372-77ee060a-ddd4-4b62-a21e-afed0c178c2e.png)

Asterrisk is ready  but cant authenticate. please help. thanks!

![image](https://user-images.githubusercontent.com/37672036/226102407-8f235a2d-bae2-40fe-8b6f-9adaa0cd2ad9.png)

**Comment by TECH7Fox** [comment]
Can you share your `manager.conf` in `/config/asterisk/default/`
Also make sure there is **no** `manager.conf` inside `/config/asterisk/custom/`

**Comment by tung256** [comment]
> Can you share your `manager.conf` in `/config/asterisk/default/` Also make sure there is **no** `manager.conf` inside `/config/asterisk/custom/`

certainly.
![image](https://user-images.githubusercontent.com/37672036/226498565-0c7f73c4-92b1-47a4-b88f-0acd8445fc3a.png)

no files here
![image](https://user-images.githubusercontent.com/37672036/226498593-f0ffb734-2a4f-4dfb-b0ec-5b2c0ec86748.png)

**Comment by TECH7Fox** [comment]
Can you try `password123` all lowercase?
What did you set as IP in the integration? Use `localhost` or `127.0.0.1`.

**Comment by tung256** [comment]
ok. im using password123 now
![image](https://user-images.githubusercontent.com/37672036/226774774-f7630104-642a-489b-8a7f-2b835ae85725.png)
![image](https://user-images.githubusercontent.com/37672036/226774861-04293260-a74a-4a13-96ae-fa774eba3b22.png)
integration now works with localhost.  i was using the IP address of my HA machine before.
![image](https://user-images.githubusercontent.com/37672036/226775179-5cab295a-d308-400a-b89d-e16aa612f6b5.png)

this next part, i dont understand....
there are 2 users. tung on 2nd floor.   linh on 1st floor.
what secret should they be using? password123   OR  the pw that they use to log into HA GUI?  for now, i am using password123.
![image](https://user-images.githubusercontent.com/37672036/226777007-072e0742-6c80-4bbb-b14e-dcfff8258d1d.png)

the card does not appear once i added it:
![image](https://user-images.githubusercontent.com/37672036/226777112-60fb8d71-fa5d-432f-ad4e-63b9d0b32be1.png)

i did contrl+F5 on firefox
do i really need DuckDNS for https?  the tablets will be used to call each other in the house, i dont plan to call remotely from outside the house.

**Comment by tung256** [comment]
Integration has no error now  but these shows as offline?  
![image](https://user-images.githubusercontent.com/37672036/226778065-65bfc1d8-93a8-46e6-bf87-ea833cf23135.png)

![image](https://user-images.githubusercontent.com/37672036/226778098-d51da702-8e37-4df9-b1c9-89bc622eb425.png)

![image](https://user-images.githubusercontent.com/37672036/226778227-bdfae9de-20a9-4f7a-beb7-79f8e66a4922.png)

**Comment by TECH7Fox** [comment]
> what secret should they be using? password123 OR the pw that they use to log into HA GUI?

The `auto_add_secret`, so in your case password123.

> do i really need DuckDNS for https?

Browsers requires SSL for a WSS connection. Easiest is to setup a duckdns, but you could also create a self-signed certificate and add a DNS rewrite to match the domain.

But you can temporary accept the certificate by going to `https://ha_ip:8089/ws` and clicking continue.

> the card does not appear once i added it

Check the console (F12) for any errors on the card.

**Comment by BigHomie90** [comment]
Same issue here...Everything was working fine till 1 or 2 previous addon updates... authentication failed for extensions and integration shows asterisk server offline.

**Comment by BigHomie90** [comment]
omg...sorry..i double checked the changelog. 

`3.0.0
Breaking Changes
We changed the way we handle the Asterisk config files and this will require a manual action on your side. Now, Asterisk files you intend to modify should be placed under /config/asterisk/custom. For example, if you were previously editing extensions.conf, you should move it from /config/asterisk/extensions.conf to /config/asterisk/custom/extensions.conf.

After moving all the files you need to /config/asterisk/custom, you can also cleanup the /config/asterisk folder by deleting everything under it, except for the custom folder.`

Everything working fine again.

**Comment by tung256** [comment]
i tried https://192.168.1.229:8089/ws  and accepted the risk when the warning came up. next, i got this 
![image](https://user-images.githubusercontent.com/37672036/227410879-9b78b28f-102d-48b1-b912-325fe02c55bb.png)

here is my card:
![image](https://user-images.githubusercontent.com/37672036/227411775-92016078-8ac5-4bd7-ae3b-9b14f0eda19f.png)



and this is the console error you requested:
[console error.txt](https://github.com/TECH7Fox/asterisk-hass-integration/files/11058004/console.error.txt)

**Comment by TECH7Fox** [comment]
Are your persons correct? Try using the config editor.

**Comment by tung256** [comment]
ok. im happy to say i got HTTPS working locally now as seen here. self signed certificate instruction from [this site](https://forum.opnsense.org/index.php?topic=26277.0)
![image](https://user-images.githubusercontent.com/37672036/227988610-a55e3e1b-d1e7-43c9-8e33-6b11217d8c06.png)

these are the 2 persons for the 2 tablets:
person.tablet_1st
person.tablet_2nd_2
they are loaded in now after taking your advice:
![image](https://user-images.githubusercontent.com/37672036/228003403-7156c7f9-a73e-49b4-9a9b-e967ed78ee47.png)

when i click on Call on the white tablet, nothing happens as seen here
![image](https://user-images.githubusercontent.com/37672036/228003984-0e356bcc-f5e0-4fb6-9209-742eba08f737.png)

really appreciate your help.  feeling so close to getting it done thanks to your time n patience too!

**Comment by TECH7Fox** [comment]
The card gives a "Person and backup not configured" error. Meaning that you don't have a extension with the currently logged in person configured. What is your card config? Did you set the correct persons?

**Comment by tung256** [comment]
i am sorry, i do not understand.
this is my code for the card
![image](https://user-images.githubusercontent.com/37672036/228406451-f4b14f98-e285-4ff5-ae46-fe84836ab444.png)


it is the only place i assign the person entity to its extension.
  person.tung   
  extension: '101'
  
  person.tablet_1st
  extension: '102'
  
  person: person.tablet_2nd_2
  extension: '103'

are you saying there are other places to assign person and extension? if so, where?
this is what i see in my Integration. strange that extension for 103 does not exist here.

![image](https://user-images.githubusercontent.com/37672036/228412971-736a465b-7441-4138-8519-aa34698c3b90.png)

and when i click on the devices, this is what i see:
![image](https://user-images.githubusercontent.com/37672036/228413202-6de5d081-b680-4e3b-b261-2cb64926f3da.png)

![image](https://user-images.githubusercontent.com/37672036/228413242-5f9134bc-5df8-4917-acc8-4378e32d2587.png)

**Comment by TECH7Fox** [comment]
You only have to set the persons in the card. But I think you aren't using those users or mistyped the users.

Make sure your current user is linked to that actual person, and that the person ID is correctly set in the card. You can use the editor to set the correct person ID.

**Comment by TECH7Fox** [comment]
I think someone else had a problem that the user wasn't actually linked to the person because of the way he made the person separately.

**Comment by tung256** [comment]
ok. i removed the person and added back.  person is working good now.  no more person and backup error.  :)
i still cannot make any call though.  when i place call, it auto terminate instantly.  F12 reveals this:
![image](https://user-images.githubusercontent.com/37672036/229370036-2ae118d8-ac9c-454d-8787-624d8eed010f.png)

**Comment by TECH7Fox** [comment]
It says the fail fails on the remote. Guessing your tablet is having a issue with the mic access. Do you use the HA companion app?

Maybe try desktop to desktop first and see if that works.

**Comment by tung256** [comment]
yes, i use the HA companion app. also tried using desktop to desktop as you suggested.

im having doubts about how a person is assigned an extension. could you pls clarify?

if i define all the extensions here:
![image](https://user-images.githubusercontent.com/37672036/229608842-9739b7a7-daf3-43e2-a0b3-d4f1c06a3278.png)




then do i turn off Auto Extension here?
![image](https://user-images.githubusercontent.com/37672036/229609160-026e05ea-9d3f-4bac-83c0-685661956d28.png)

im using local self sign certificate, not duckddns.  do i still put a check mark for Asterisk  or disable it as seen here?
![image](https://user-images.githubusercontent.com/37672036/229609567-7beeb17c-d0fb-403f-9762-0c000fc26c15.png)

**Comment by TECH7Fox** [comment]
Keep "generate SSL certificate" disabled. 
And turn on the 'auto add extensions" options. 

The card choses the extension based on the current logged in user. It chooses the extension with the person that is for the current user.

You can look at the config/asterisk/default/pjsip_default.conf file for the generated extensions.

**Comment by TECH7Fox** [comment]
Btw, I recommend asking on the Discord server. There are examples and more people there to help. Link is underneath the docs website.

**Comment by TECH7Fox** [comment]
Closing for now. Let me know if your still having a issue.
