### ISSUE TITLE
Memory leak.

### ISSUE THREAD

**Issue by Bram-diederik** [TECH7Fox/asterisk-hass-integration#73]
I had the integration connected to my native asterisk. And it has a (recent) memory leak.

I have 13 devices and 50 entities.

Its a pain to find a memory leak inside an integration.

![Screenshot_20230410_102325_Home Assistant](https://user-images.githubusercontent.com/53519837/230867838-640f52ff-5cc9-4773-a4c5-1e2006fc87c8.jpg)

**Comment by TECH7Fox** [comment]
Rework is almost done. Hope that fixes it.

**Comment by TECH7Fox** [comment]
Rework is merged in v1.0.0. Is it still having the same issue?

**Comment by TECH7Fox** [comment]
Please reopen if this is still a issue.
