### ISSUE TITLE
Config entry 'nas.lan' for asterisk integration not ready yet: 'str' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by andyboeh** [TECH7Fox/asterisk-hass-integration#81]
Hi,
I just updated to 1.0 and now the integration doesn't start anymore:
```
Config entry 'nas.lan' for asterisk integration not ready yet: 'str' object cannot be interpreted as an integer
```
Do I need to change something in the configuration that I missed?

Edit: I just removed and re-added the integration, now it's starting properly.

**Comment by TECH7Fox** [comment]
Yes the old config does not work anymore. Re-add it and it should work fine.
