### ISSUE TITLE
How to use new service call

### ISSUE THREAD

**Issue by andyboeh** [TECH7Fox/asterisk-hass-integration#82]
I had a bunch of calls to `asterisk.originate` in my automations, they now stopped working. I saw that only one service is provided now (`asterisk.send_action`), but how can it be used to replace `asterisk.originate`? Did I miss the documentation on the new service? I'm only aware of the (now probably outdated) documentation at https://tech7fox.github.io/sip-hass-docs/docs/integration/services/originate

Thanks

**Comment by TECH7Fox** [comment]
The documentation is not updated yet.
But basicly, in action you set `Originate` and then all the other settings you set in parameters.
Here are all the Originate parameters: https://wiki.asterisk.org/wiki/display/AST/Asterisk+11+ManagerAction_Originate

**Comment by andyboeh** [comment]
Thanks, I'm going to try it on the weekend, I'm positive it will work!

Thanks for all the great work on this!

**Comment by TECH7Fox** [comment]
I updated the docs. There are some examples there.

**Comment by fernac03** [comment]
hi,  asterisk.send_action  not  working 
in  asterisk debug manager  i receive  "Action: Originate
Channel: PJSIP/205
Exten: 123@speech
Priority: 1
Timeout: 60000
ActionID: 58075
"
but extension 205  not  ring  
on asterisk cli   i use  channel originate PJSIP/205 extension 123@speech   the  extension 205  ring

**Comment by fernac03** [comment]
i found  a response   this  is  a example  that  how  the  service 

action: asterisk.send_action
metadata: {}
data:
  action: Originate
  parameters:
    Channel: SIP/202
    Context: speech
    Exten: "123"
    Priority: 1
    Timeout: 60000
