### ISSUE TITLE
Asterisk won`t load extensions.conf @ custom folder

### ISSUE THREAD

**Issue by Davensen** [TECH7Fox/asterisk-hass-integration#94]
Asterisk Addon on HACS wont load my extensions.conf @ /config/custom  

file looks like:

; Note: this file has been modified from the Asterisk defaults for the add-on

exten => 1111,1,NoOp
  same => n,Playback(doorbell-short)
  same => n,Wait(1)
  same => n,Hangup()
;
[parkedcallstimeout]
exten => s,1,Hangup()

-> if there is a custom config file, a symbolic link is created on top of the default config file pointing to the custom config file - asterik didnt create a symbolic link - why ?

**Comment by vlavrynovych** [comment]
Hi @Davensen , shoudn't it be in the `/config/asterisk/custom/extensions.conf`?

In my case it works perfectly. See the attached screenshot.

![Screenshot 2023-12-28 at 23 18 36](https://github.com/TECH7Fox/asterisk-hass-integration/assets/940468/9967dd96-40dc-4aed-af98-409896911f03)

**Comment by TECH7Fox** [comment]
@Davensen did you check if you placed it in the correct location?
Make sure to restart the add-on to see your changes.

**Comment by TECH7Fox** [comment]
Will close for now. If you're still having this issue please let me know
