### ISSUE TITLE
Question - triggers

### ISSUE THREAD

**Issue by vantech14** [TECH7Fox/asterisk-hass-integration#95]
Hi, 

Am I able to use this integration to trigger a HA automaton, when a ring group is called? 

Thanks.

**Comment by vlavrynovych** [comment]
Hi @vantech14 , I belive that yes, please check attributes of Connected Line
You can even create a sepeate virtual sensors for any of the needed attributes and use them in your automations

Below you can find all the attributes that it has
![Screenshot 2023-12-28 at 23 32 51](https://github.com/TECH7Fox/asterisk-hass-integration/assets/940468/b2d416e3-15c6-41fa-a806-ccd7e8cd7bc6)
